"""Seed catalog for the Pulse rigged demo: 12 categories, deep-ish.

Structure:
  CATEGORIES: list of (slug, name, color)
  OBJECTS[slug]: list of (canonical_name, object_type, [aliases])
  MARKETS[slug]: list of (prompt, object_type)

Markets reference an object_type; the feed/search constrain candidates to that
type within the category. Aliases feed the fuzzy search.
"""

CATEGORIES = [
    ("music", "Music", "#6C5CE7"),
    ("film-tv", "Film & TV", "#E17055"),
    ("anime-manga", "Anime & Manga", "#0984E3"),
    ("gaming", "Gaming", "#00B894"),
    ("internet", "Internet & Memes", "#FD79A8"),
    ("sports", "Sports", "#E84393"),
    ("fashion", "Fashion & Style", "#2D3436"),
    ("food-drink", "Food & Drink", "#FDCB6E"),
    ("books-writing", "Books & Writing", "#A29BFE"),
    ("people", "People", "#00CEC9"),
    ("places", "Places & Travel", "#55EFC4"),
    ("brands-products", "Brands & Products", "#636E72"),
]

OBJECTS = {
    "music": [
        ("Nights — Frank Ocean", "song", ["nights", "nights frank", "nights blonde"]),
        ("Blinding Lights — The Weeknd", "song", ["blinding lights", "weeknd blinding"]),
        ("Bohemian Rhapsody — Queen", "song", ["bohemian rhapsody", "queen bohemian"]),
        ("Sicko Mode — Travis Scott", "song", ["sicko mode", "sicko"]),
        ("Kesariya — Arijit Singh", "song", ["kesariya", "brahmastra song"]),
        ("HUMBLE. — Kendrick Lamar", "song", ["humble", "humble kendrick"]),
        ("One Dance — Drake", "song", ["one dance", "drake one dance"]),
        ("Levitating — Dua Lipa", "song", ["levitating", "dua lipa levitating"]),
        ("Frank Ocean", "artist", ["frank ocean", "frank"]),
        ("Kendrick Lamar", "artist", ["kendrick", "kendrick lamar", "kdot"]),
        ("Taylor Swift", "artist", ["taylor swift", "taylor", "tswift"]),
        ("The Weeknd", "artist", ["the weeknd", "weeknd", "abel"]),
        ("Arijit Singh", "artist", ["arijit", "arijit singh"]),
        ("Blonde — Frank Ocean", "album", ["blonde", "blonde album"]),
        ("good kid m.A.A.d city", "album", ["gkmc", "good kid maad city"]),
        ("1989 — Taylor Swift", "album", ["1989", "taylor 1989"]),
    ],
    "film-tv": [
        ("Pulp Fiction", "film", ["pulp fiction", "pulp"]),
        ("The Dark Knight", "film", ["dark knight", "the dark knight", "batman nolan"]),
        ("Parasite", "film", ["parasite", "gisaengchung"]),
        ("Inception", "film", ["inception"]),
        ("RRR", "film", ["rrr", "rise roar revolt"]),
        ("Interstellar", "film", ["interstellar"]),
        ("Breaking Bad", "tv_show", ["breaking bad", "bb"]),
        ("Squid Game", "tv_show", ["squid game", "squidgame"]),
        ("Fleabag", "tv_show", ["fleabag"]),
        ("Game of Thrones", "tv_show", ["got", "game of thrones"]),
        ("Anton Chigurh", "character", ["anton chigurh", "chigurh"]),
        ("Joker", "character", ["joker", "the joker"]),
        ("Walter White", "character", ["walter white", "heisenberg"]),
        ("Christopher Nolan", "director", ["nolan", "christopher nolan"]),
        ("Bong Joon-ho", "director", ["bong joon ho", "bong"]),
    ],
    "anime-manga": [
        ("Jujutsu Kaisen", "anime", ["jjk", "jujutsu kaisen", "jujutsu"]),
        ("Attack on Titan", "anime", ["aot", "attack on titan", "shingeki"]),
        ("Demon Slayer", "anime", ["demon slayer", "kimetsu"]),
        ("Spirited Away", "anime", ["spirited away", "ghibli spirited"]),
        ("One Piece", "anime", ["one piece", "op"]),
        ("Berserk", "manga", ["berserk"]),
        ("Vagabond", "manga", ["vagabond"]),
        ("Chainsaw Man", "manga", ["chainsaw man", "csm"]),
        ("Gojo Satoru", "character", ["gojo", "satoru gojo"]),
        ("Levi Ackerman", "character", ["levi", "levi ackerman"]),
        ("Eren Yeager", "character", ["eren", "eren yeager"]),
        ("Studio Ghibli", "studio", ["ghibli", "studio ghibli"]),
        ("MAPPA", "studio", ["mappa"]),
    ],
    "gaming": [
        ("Elden Ring", "game", ["elden ring", "elden"]),
        ("The Last of Us", "game", ["last of us", "tlou"]),
        ("Red Dead Redemption 2", "game", ["rdr2", "red dead 2", "red dead redemption"]),
        ("The Witcher 3", "game", ["witcher 3", "witcher"]),
        ("Genshin Impact", "game", ["genshin", "genshin impact"]),
        ("Hollow Knight", "game", ["hollow knight"]),
        ("God of War", "game", ["god of war", "gow"]),
        ("Minecraft", "game", ["minecraft"]),
        ("Master Chief", "game_character", ["master chief", "chief"]),
        ("Kratos", "game_character", ["kratos"]),
        ("Geralt of Rivia", "game_character", ["geralt", "geralt of rivia"]),
        ("FromSoftware", "studio", ["fromsoftware", "from software", "fromsoft"]),
        ("Rockstar Games", "studio", ["rockstar", "rockstar games"]),
    ],
    "internet": [
        ("Skibidi Toilet", "meme", ["skibidi", "skibidi toilet"]),
        ("Hawk Tuah", "meme", ["hawk tuah", "hawktuah"]),
        ("Distracted Boyfriend", "meme", ["distracted boyfriend"]),
        ("Doge", "meme", ["doge", "such wow"]),
        ("Oh No — Kreepa", "sound", ["oh no", "oh no sound"]),
        ("Original Sound — Tax", "sound", ["tax sound", "oh no oh no"]),
        ("POV", "format", ["pov", "point of view"]),
        ("Tier List", "format", ["tier list", "tierlist"]),
        ("MrBeast", "creator", ["mrbeast", "mr beast"]),
        ("Speed", "creator", ["ishowspeed", "speed"]),
        ("Kai Cenat", "creator", ["kai cenat", "kai"]),
    ],
    "sports": [
        ("Lionel Messi", "athlete", ["messi", "lionel messi", "leo messi"]),
        ("Cristiano Ronaldo", "athlete", ["ronaldo", "cr7", "cristiano"]),
        ("Virat Kohli", "athlete", ["kohli", "virat", "virat kohli"]),
        ("LeBron James", "athlete", ["lebron", "lebron james", "king james"]),
        ("Max Verstappen", "athlete", ["verstappen", "max verstappen"]),
        ("MS Dhoni", "athlete", ["dhoni", "ms dhoni", "thala"]),
        ("Real Madrid", "team", ["real madrid", "madrid"]),
        ("Mumbai Indians", "team", ["mi", "mumbai indians"]),
        ("Argentina NT", "team", ["argentina", "argentina national team"]),
        ("Aguero 93:20", "moment", ["aguero 9320", "aguero moment"]),
        ("Dhoni 2011 Six", "moment", ["dhoni six", "2011 world cup final"]),
    ],
    "fashion": [
        ("Air Jordan 1", "sneaker", ["jordan 1", "aj1", "air jordan 1"]),
        ("Nike Dunk Low", "sneaker", ["dunk low", "nike dunk"]),
        ("New Balance 550", "sneaker", ["nb 550", "new balance 550"]),
        ("Samba — Adidas", "sneaker", ["samba", "adidas samba"]),
        ("Telfar", "brand", ["telfar"]),
        ("Stussy", "brand", ["stussy"]),
        ("Prada", "brand", ["prada"]),
        ("Old Money", "person", ["old money aesthetic", "old money"]),
        ("Labubu", "product", ["labubu"]),
        ("Stanley Quencher", "product", ["stanley", "stanley cup", "quencher"]),
    ],
    "food-drink": [
        ("Biryani", "dish", ["biryani", "biriyani"]),
        ("Butter Chicken", "dish", ["butter chicken", "murgh makhani"]),
        ("Maggi", "dish", ["maggi", "maggie"]),
        ("Masala Dosa", "dish", ["dosa", "masala dosa"]),
        ("Pani Puri", "dish", ["pani puri", "golgappa", "puchka"]),
        ("Filter Coffee", "drink", ["filter coffee", "filter kaapi"]),
        ("Old Monk", "drink", ["old monk", "rum old monk"]),
        ("Masala Chai", "drink", ["chai", "masala chai"]),
        ("South Indian", "cuisine", ["south indian", "south indian food"]),
        ("North Indian", "cuisine", ["north indian", "north indian food"]),
    ],
    "books-writing": [
        ("1984 — George Orwell", "book", ["1984", "nineteen eighty four"]),
        ("Sapiens", "book", ["sapiens"]),
        ("Dune", "book", ["dune"]),
        ("The Alchemist", "book", ["alchemist", "the alchemist"]),
        ("Norwegian Wood", "book", ["norwegian wood"]),
        ("Atomic Habits", "book", ["atomic habits"]),
        ("Haruki Murakami", "author", ["murakami", "haruki murakami"]),
        ("George Orwell", "author", ["orwell", "george orwell"]),
        ("Yuval Noah Harari", "author", ["harari", "yuval harari"]),
    ],
    "people": [
        ("MrBeast", "creator", ["mrbeast", "mr beast"]),
        ("Zendaya", "person", ["zendaya"]),
        ("Elon Musk", "person", ["elon", "elon musk", "musk"]),
        ("Taylor Swift", "person", ["taylor swift", "taylor"]),
        ("Virat Kohli", "person", ["virat kohli", "kohli"]),
        ("Sam Altman", "person", ["sam altman", "altman"]),
        ("CarryMinati", "creator", ["carryminati", "carry", "ajey nagar"]),
        ("Technoblade", "influencer", ["technoblade", "techno"]),
    ],
    "places": [
        ("Goa", "place", ["goa"]),
        ("Tokyo", "city", ["tokyo"]),
        ("Bengaluru", "city", ["bengaluru", "bangalore", "blr"]),
        ("Manali", "place", ["manali"]),
        ("Indiranagar", "venue", ["indiranagar", "indranagar"]),
        ("Paris", "city", ["paris"]),
        ("Pondicherry", "place", ["pondicherry", "pondy"]),
        ("New York", "city", ["new york", "nyc"]),
    ],
    "brands-products": [
        ("iPhone", "product", ["iphone", "apple iphone"]),
        ("ChatGPT", "product", ["chatgpt", "gpt"]),
        ("Stanley Quencher", "product", ["stanley", "stanley cup", "quencher"]),
        ("Labubu", "product", ["labubu"]),
        ("Tesla", "brand", ["tesla"]),
        ("Apple", "brand", ["apple"]),
        ("Nike", "brand", ["nike"]),
        ("Notion", "product", ["notion"]),
    ],
}

# Fake leaderboard competitors (name, coins, pulse)
BOTS = [
    ("CultureGoblin", 2840, 410),
    ("TasteOracle", 2610, 380),
    ("VibeChecker", 2200, 330),
    ("Aarav", 1980, 300),
    ("indie_sleaze", 1740, 270),
    ("MainCharacter", 1520, 240),
    ("frfr_no_cap", 1310, 210),
    ("the_contrarian", 1120, 180),
    ("ChartWatcher", 940, 150),
    ("lurker99", 760, 120),
    ("certified_yapper", 580, 95),
    ("nightcore_dev", 410, 70),
]
